name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup CRuby
      uses: ruby/setup-ruby@v1.66.0
      with:
        ruby-version: 3.0.0
    - name: Setup mruby
      run: |
        git clone -b 3.1.0 https://github.com/mruby/mruby.git
        cd mruby
        rake
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    - name: Build PicoRuby
      run: rake
    - name: Test with mruby/c
      run: build/repos/host/mruby-pico-compiler/test/helper/test.rb
      env:
        MRUBY_COMMAND: $PWD/bin/picoruby
    - name: Test with mruby
      run: build/repos/host/mruby-pico-compiler/test/helper/test.rb
      env:
        USE_MRUBY: yes
        PICORBC_COMMAND: $PWD/bin/picorbc
        MRUBY_COMMAND: $PWD/mruby/bin/mruby
